import { Project } from "@/lib/types/project";
export const projects: Project[] = [
  {
    id: "marhbabik",
    title: "MarhbaBik",
    category: "Mobile App",
    description: "All-in-one Algerian tourism app for discovering destinations, hotels, and tours with multi-role authentication and secure payments.",
    fullDescription: "MarhbaBik is an all-in-one tourism mobile app for discovering Algerian destinations, hotels, and tours. It supports multiple user types including tourists and service providers, features multi-role authentication with dynamic UI rendering, integrated third-party payment gateway with secure transaction handling, Firebase services (Authentication, Firestore, Storage, FCM), and smooth booking flows with clean UI.",
    features: ["Multi-role Auth", "Secure Payments", "Booking System"],
    techStack: [
      { name: "Flutter", color: "text-accent-green bg-accent-green/10" },
      { name: "Firebase", color: "text-accent-red bg-accent-red/10" },
      { name: "Dart", color: "text-accent-blue bg-accent-blue/10" },
    ],
    previewImage: "/images/projects/MarhbaBik/screen-1.jpg",
    screenshots: {
      platform: "mobile",
      images: [
        "/images/projects/MarhbaBik/screen-1.jpg",
        "/images/projects/MarhbaBik/screen-2.jpg",
        "/images/projects/MarhbaBik/screen-3.jpg",
        "/images/projects/MarhbaBik/screen-4.jpg",
        "/images/projects/MarhbaBik/screen-5.jpg",
        "/images/projects/MarhbaBik/screen-6.jpg",
        "/images/projects/MarhbaBik/screen-7.jpg",
        "/images/projects/MarhbaBik/screen-8.jpg",
        "/images/projects/MarhbaBik/screen-9.jpg",
        "/images/projects/MarhbaBik/screen-10.jpg",
        "/images/projects/MarhbaBik/screen-11.jpg",
        "/images/projects/MarhbaBik/screen-12.jpg",
        "/images/projects/MarhbaBik/screen-13.jpg",
        "/images/projects/MarhbaBik/screen-14.jpg",
        "/images/projects/MarhbaBik/screen-15.jpg",
      ],
    },
    links: { github: "https://github.com/" },
  },
  {
    id: "marhbabik-platform",
    title: "MarhbaBik Platform",
    category: "Web App",
    description: "Web platform for the MarhbaBik tourism ecosystem with authentication, Firestore database, and storage management for service providers.",
    fullDescription: "MarhbaBik Platform is the web companion to the MarhbaBik mobile app, providing a full-featured dashboard for managing the tourism ecosystem. Built with React and TypeScript, it features Firebase Authentication for multi-role access, Firestore for real-time data management, and Firebase Storage for media handling.",
    features: ["Multi-role Dashboard", "Real-time Data", "Media Management"],
    techStack: [
      { name: "React", color: "text-accent-blue bg-accent-blue/10" },
      { name: "TypeScript", color: "text-accent-blue bg-accent-blue/10" },
      { name: "Tailwind CSS", color: "text-accent-teal bg-accent-teal/10" },
      { name: "Firebase", color: "text-accent-red bg-accent-red/10" },
    ],
    previewImage: "/images/projects/MarhbaBik-Platform/screen-1.png",
    screenshots: {
      platform: "web",
      images: [
        "/images/projects/MarhbaBik-Platform/screen-1.png",
        "/images/projects/MarhbaBik-Platform/screen-2.png",
        "/images/projects/MarhbaBik-Platform/screen-3.png",
        "/images/projects/MarhbaBik-Platform/screen-4.png",
        "/images/projects/MarhbaBik-Platform/screen-5.png",
        "/images/projects/MarhbaBik-Platform/screen-6.png",
        "/images/projects/MarhbaBik-Platform/screen-7.png",
        "/images/projects/MarhbaBik-Platform/screen-8.png",
        "/images/projects/MarhbaBik-Platform/screen-9.png",
        "/images/projects/MarhbaBik-Platform/screen-10.png",
        "/images/projects/MarhbaBik-Platform/screen-11.png",
        "/images/projects/MarhbaBik-Platform/screen-12.png",
        "/images/projects/MarhbaBik-Platform/screen-13.png",
        "/images/projects/MarhbaBik-Platform/screen-14.png",
      ],
    },
    links: { github: "https://github.com/" },
  },
  {
    id: "previva",
    title: "Previva",
    category: "Mobile App",
    description: "Medical document management app focused on health tracking, secure document storage, and usability-first design.",
    fullDescription: "Previva is an MVP health tracking mobile app that enables users to securely store and manage medical documents. The app prioritizes usability, core health features, and data security to provide a reliable personal health management experience.",
    features: ["Document Storage", "Health Tracking", "Data Security"],
    techStack: [
      { name: "Flutter", color: "text-accent-green bg-accent-green/10" },
      { name: "Firebase", color: "text-accent-red bg-accent-red/10" },
    ],
    previewImage: "/images/projects/Previva/screen-1.png",
    screenshots: {
      platform: "mobile",
      images: [
        "/images/projects/Previva/screen-1.png",
        "/images/projects/Previva/screen-2.png",
        "/images/projects/Previva/screen-3.png",
        "/images/projects/Previva/screen-4.png",
        "/images/projects/Previva/screen-5.png",
        "/images/projects/Previva/screen-6.png",
        "/images/projects/Previva/screen-7.png",
        "/images/projects/Previva/screen-8.png",
        "/images/projects/Previva/screen-9.png",
        "/images/projects/Previva/screen-10.png",
      ],
    },
    links: { github: "https://github.com/" },
  },
];
